input { 
  file {
    path => "/app/weblog.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  if [message] =~ "^IP," {
    drop {}
  }

  csv {
    separator => ","
    columns => ["client_ip", "timestamp", "request", "status_code"]
  }
  date {
    match => ["timestamp", "[dd/MMM/yyyy:HH:mm:ss"]
    target => "@timestamp"
  }

  mutate {
    convert => { "status_code" => "integer" }
    remove_field => ["timestamp", "message", "host", "path", "@version"]
  }
}

output {
  elasticsearch {
    hosts => "elasticsearch"
    index => "clickstream-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
